plugins {
    id 'base'
    id 'jacoco'
    id 'io.gatling.gradle' version '3.15.0.3' apply false
}

allprojects {
    group = 'com.senthora.gatlingfx'
    version = '0.1.0'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'jacoco'

    base {
        archivesName = "${rootProject.name}-${project.name}"
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    jacoco {
        toolVersion = '0.8.14'
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()

        testLogging {
            events "passed", "skipped", "failed"
            showStandardStreams = true
        }

        finalizedBy tasks.jacocoTestReport
    }

    tasks.jacocoTestReport {
        dependsOn tasks.test

        reports {
            xml.required = true
            html.required = true
        }
    }

    dependencies {
        testImplementation platform(libs.junit.bom)
        testImplementation libs.junit.jupiter
        testRuntimeOnly libs.junit.platform.launcher

        testImplementation libs.assertj.core
    }
}

tasks.register('jacocoTestReport', JacocoReport) {
    dependsOn subprojects.collectMany { project ->
        project.tasks.matching {
            it.name in ['test', 'integrationTest']
        }
    }
    dependsOn subprojects.collect { it.tasks.named('jacocoTestReport') }

    additionalSourceDirs.from files(subprojects.sourceSets.main.allSource.srcDirs)
    sourceDirectories.from files(subprojects.sourceSets.main.allSource.srcDirs)
    classDirectories.from files(subprojects.sourceSets.main.output)

    executionData.from fileTree(layout.projectDirectory) {
        include '**/build/jacoco/*.exec'
    }
    reports {
        xml.required = true
        html.required = true

        xml.outputLocation = layout.buildDirectory.file(
                'reports/jacoco/jacocoRootReport.xml'
        )
        html.outputLocation = layout.buildDirectory.dir(
                'reports/jacoco/html'
        )
    }
}

tasks.named('clean') {
    delete layout.buildDirectory
}
