plugins {
    id 'java'
    id "io.gatling.gradle" version "3.15.0.3"
}

group = 'io.github.meowpowpng'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.assertj.core
    implementation libs.bundles.gatling

    testImplementation platform(libs.junit.bom)
    testImplementation libs.junit.jupiter
    testRuntimeOnly libs.junit.platform.launcher

    testImplementation platform(libs.mockito.bom)
    testImplementation libs.mockito.core
}

test {
    useJUnitPlatform()
}
