plugins {
    id 'base'
    id 'io.gatling.gradle' version '3.15.0.3' apply false
}

allprojects {
    group = 'com.senthora.gatlingfx'
    version = '0.1.0'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'

    base {
        archivesName = "${rootProject.name}-${project.name}"
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()

        testLogging {
            events "passed", "skipped", "failed"
            showStandardStreams = true
        }
    }

    dependencies {
        testImplementation platform(libs.junit.bom)
        testImplementation libs.junit.jupiter
        testRuntimeOnly libs.junit.platform.launcher

        testImplementation libs.assertj.core
    }
}

tasks.named('clean') {
    delete layout.buildDirectory
}
