pluginManagement {
    repositories {
        maven {
            url = uri('https://central.sonatype.com/repository/maven-snapshots/')
        }
        gradlePluginPortal()
    }
}
rootProject.name = 'gatlingfx'

include 'core'
include 'runtime'
include 'runtime-api'
include 'proxy'
include 'wiremock'

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")
