map $upstream_addr $upstream_fmt {
    "" "";
    default "-> $upstream_addr -> ";
}
map $upstream_response_time $urt_fmt {
    "" "";
    "-" "";
    default "urt=$upstream_response_time ";
}
access_log off;
log_format proxy_access
  '[$time_iso8601] '
  '[cfproxy] '
  '$remote_addr -- $request_method "$request_uri" $host '
  '$upstream_fmt$status '
  'xff=[$http_x_forwarded_for] '
  'rt=$request_time $urt_fmt';
