dependencies {
    implementation projects.core

    implementation libs.classgraph
    implementation platform(libs.junit.bom)
    implementation libs.junit.jupiter.api
    implementation libs.junit.platform.engine

    implementation libs.gatling.app
    implementation libs.gatling.charts
    implementation "io.gatling.highcharts:gatling-charts-highcharts:3.15.0"
}

testing {
    suites {
        integrationTest(JvmTestSuite) {
            dependencies {
                implementation libs.junit.platform.testkit
                implementation libs.gatling.app

                implementation platform(libs.mockito.bom)
                implementation libs.mockito.core
            }
            targets {
                all {
                    testTask.configure {
                        useJUnitPlatform {
                            excludeEngines("gatlingfx")
                        }
                    }
                }
            }
        }
    }
}
