dependencies {
    implementation projects.core

    implementation libs.classgraph
    implementation platform(libs.junit.bom)
    implementation libs.junit.jupiter.api
    implementation libs.junit.platform.engine

    implementation libs.gatling.app
    implementation libs.gatling.charts
    implementation "io.gatling.highcharts:gatling-charts-highcharts:3.15.0"
}
