server {
    listen 80;
    server_name _;

    location = /order/coffee {
        return 418;
    }

    location = /order/tea {
        default_type application/json;
        return 201 '{"drink":"tea","temperature":"volcanic","leaves":"probably"}';
    }

    location / {
        return 404;
    }
}
