[versions]
gatling = "3.15.0"
assertj = "3.27.7"
junit = "6.0.3"
mockito = "5.23.0"

[libraries]
gatling-core = { module = "io.gatling:gatling-core-java", version.ref = "gatling" }
gatling-http = { module = "io.gatling:gatling-http-java", version.ref = "gatling" }

assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

mockito-bom = { module = "org.mockito:mockito-bom", version.ref = "mockito" }
mockito-core = { module = "org.mockito:mockito-core" }

[bundles]
gatling = [
    "gatling-core",
    "gatling-http"
]
