[versions]
gatling = "3.15.0"
assertj = "3.27.7"
junit = "6.0.3"
mockito = "5.23.0"
mockwebserver = "5.3.2"
classgraph = "4.8.184"
picocli = "4.7.7"

[libraries]
gatling-core = { module = "io.gatling:gatling-core-java", version.ref = "gatling" }
gatling-http = { module = "io.gatling:gatling-http-java", version.ref = "gatling" }
gatling-app = { module = "io.gatling:gatling-app", version.ref = "gatling" }
gatling-charts = { module = "io.gatling.highcharts:gatling-charts-highcharts", version.ref = "gatling" }

classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }

junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }

junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
junit-platform-engine = { module = "org.junit.platform:junit-platform-engine" }
junit-platform-testkit = { module = "org.junit.platform:junit-platform-testkit" }

assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }

mockito-bom = { module = "org.mockito:mockito-bom", version.ref = "mockito" }
mockito-core = { module = "org.mockito:mockito-core" }

mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
