plugins {
    id 'java-test-fixtures'
}

dependencies {
    api libs.gatling.core
    api libs.gatling.http

    testImplementation platform(libs.mockito.bom)
    testImplementation libs.mockito.core
}

testing {
    suites {
        integrationTest(JvmTestSuite) {
            dependencies {
                implementation projects.core

                implementation platform(libs.junit.bom)
                implementation libs.junit.jupiter
                implementation libs.mockwebserver
                implementation libs.assertj.core
            }
            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(tasks.test)
                    }
                }
            }
        }
    }
}
