plugins {
    id 'java-test-fixtures'
}

dependencies {
    api libs.bundles.gatling

    testImplementation platform(libs.mockito.bom)
    testImplementation libs.mockito.core

    testFixturesImplementation platform(libs.junit.bom)
    testFixturesImplementation libs.junit.jupiter
    testFixturesImplementation libs.mockwebserver
}

testing {
    suites {
        integrationTest(JvmTestSuite) {
            dependencies {
                implementation libs.mockwebserver
            }
            targets {
                all {
                    testTask.configure {
                        shouldRunAfter(tasks.test)
                    }
                }
            }
        }
    }
}

configurations {
    integrationTestImplementation.extendsFrom(testImplementation)
    integrationTestRuntimeOnly.extendsFrom(testRuntimeOnly)
}

tasks.named("check") {
    dependsOn(testing.suites.integrationTest)
}
