plugins {
    id 'java-test-fixtures'
}

dependencies {
    api libs.gatling.core
    api libs.gatling.http

    testImplementation platform(libs.mockito.bom)
    testImplementation libs.mockito.core

    testFixturesApi libs.mockwebserver
    testFixturesImplementation platform(libs.junit.bom)
    testFixturesImplementation libs.junit.jupiter.api
}
