name: CI

on:
  workflow_dispatch:
  push:
    branches: [ master, dev ]
    paths:
      - ".github/workflows/**"
      - "build.gradle"
      - "settings.gradle"
      - "gradle.properties"
      - "gradle/**"
      - "gradlew"
      - "gradlew.bat"
      - "core/**"
      - "proxy/**"
      - "runtime/**"
      - "wiremock/**"
      - '!**/*.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build
        run: ./gradlew build -x test -x integrationTest

      - name: Run tests
        run: ./gradlew test integrationTest
