plugins {
    id 'java'
}

dependencies {
    implementation projects.core
    implementation projects.runtime
    implementation projects.proxy
    implementation projects.wiremock

    implementation libs.jspecify

    testImplementation projects.runtime
}

tasks.register("gatlingFx", JavaExec) {
    group = "verification"
    description = "Runs GatlingFx simulations"

    classpath = sourceSets.main.runtimeClasspath
    mainClass = "com.senthora.gatlingfx.runtime.application.GatlingFx"

    jvmArgs("--add-opens=java.base/java.lang=ALL-UNNAMED")
}
